# Generated by Django 4.2.3 on 2023-07-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SIM', 'Simple'), ('DBL', 'Double'), ('MAT', 'Matrimonial'), ('SPL', 'Special')], default='SIM', max_length=3, verbose_name='Room Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Price per Day')),
                ('discount_rate', models.PositiveIntegerField(default=0, verbose_name='Discount Rate')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['type'],
            },
        ),
    ]
