# Generated by Django 4.2.3 on 2023-07-21 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Deleted Date')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Tarjeta Credito'), ('CASH', 'Efectivo'), ('QR', 'QR')], max_length=50)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalInvoice',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Updated Date')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Deleted Date')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Tarjeta Credito'), ('CASH', 'Efectivo'), ('QR', 'QR')], max_length=50)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('booking', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='booking.booking')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Invoice',
                'verbose_name_plural': 'historical Invoices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
