# Generated by Django 4.2.3 on 2023-07-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Tarjeta Credito'), ('DEBIT_CARD', 'Tarjeta Debito'), ('CASH', 'Efectivo'), ('QR', 'QR')], max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Tarjeta Credito'), ('DEBIT_CARD', 'Tarjeta Debito'), ('CASH', 'Efectivo'), ('QR', 'QR')], max_length=50),
        ),
    ]
